name: CI CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Dotnet restore packages
        run: dotnet restore
      
      - name: Dotnet build
        run: dotnet build
      
      - name: Dotnet publish
        run: dotnet publish
