name: CI CD(dev)

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Dotnet restore packages
        run: dotnet restore
      
      - name: Dotnet build
        run: dotnet build --configuration debug
      
      - name: Dotnet publish
        run: dotnet publish
      
      - name: Upload Build Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Publish
          path: /home/runner/work/CICD/CICD/TestCICD/bin/Debug/netcoreapp3.1/publish/
